name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Configure AWS Credentials using the role
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.4.5'

      # Terraform Init
      - name: Terraform Init
        run: terraform init

      # Terraform Plan
      - name: Terraform Plan
        run: terraform plan

      # Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve

      # Setup Packer
      - name: Setup Packer
        uses: hashicorp/setup-packer@v1

      # Build AMI with Packer
      - name: Build AMI with Packer
        run: |
          packer build packer.json

      # Install Ansible and Run Playbook
      - name: Install Ansible
        run: sudo apt update && sudo apt install ansible -y

      - name: Run Ansible Playbook
        run: ansible-playbook playbook.yml --inventory hosts --private-key ~/.ssh/id_rsa
